#
# Forked from  ioggstream/bandit-report-artifacts
#
name: "super-sast-action"
description: "Github action to find common security issues in your project and get its report as annotations and an artifact."
author: "fantasticiniandrea@gmail.com"

inputs:
  project_path:
    description: "This is the path at which the your python project is located in you github repo."
    required: false
    default: "."

  ignore_failure:
    description: "This is to ignore the security failures and pass the check."
    required: false
    default: false

  # Is this still necessary?
  bandit_config_file:
    description: "The yaml config file to use"
    required: false
    default: ""

  repo_token:
    required: true
    description: |
      The GitHub App installation access token.
      [Learn more about `GITHUB_TOKEN`](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret)
    default: ${{ github.token }}

  m2_home:
    description: "java validators will be installed in this directory"
    required: false
    default: "/github/workspace"

  home:
    description: ""
    required: false
    default: "/github/workspace"

  local:
    description: "Do not call github APIs. Just run tests locally."
    required: false
    default: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "shield"
  color: "gray-dark"
