name: super-sast-action_local_container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_API_URL: ${{ github.api_url }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.7' ]
    name: Docker - Python:${{ matrix.python-version }} - OS:${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t super-sast-action:1.0 .

    - name: Run Docker Image
      run: |
        ls -lah
        docker run --name super-sast-action -v $PWD:/code -e INPUT_IGNORE_FAILURE=true -e INPUT_M2_HOME=/code -e INPUT_HOME=/code -e GITHUB_API_URL=${{ github.api_url }} -e GITHUB_REPOSITORY=${{ github.repository }} -e GITHUB_SHA=${{ github.sha }} -e INPUT_REPO_TOKEN=${{ github.token }} -w /code -u "$(id -u)" super-sast-action:1.0

    - uses: actions/upload-artifact@v3
      with:
        name: super-sast-action_artifact
        path: |
          super-sast.log
          log_dir/
