name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker-compose build --pull --force-rm test
    - name: Test
      run: |
        pwd
        ls -lah
        docker-compose run --rm test
