name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_API_URL: ${{ github.api_url }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.7' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
    - name: GitHub env variables
      run: |
        echo "$GITHUB_API_URL"
        echo "$GITHUB_REPOSITORY"
        echo "$GITHUB_SHA"
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t super-sast-action:0.4 .

    - name: Run Docker Image
      run: |
        docker run --name super-sast-artifact -v $PWD:/code -e M2_HOME=/code -e HOME=/code -e RUN_ALL_TOOLS=false -e RUN_BANDIT=true -e RUN_SAFETY=true -e GITHUB_API_URL=${{ github.api_url }} -e GITHUB_REPOSITORY=${{ github.repository }} -e GITHUB_SHA=${{ github.sha }} -e INPUT_REPO_TOKEN=${{ github.token }} -w /code super-sast-action:0.4

    - uses: actions/upload-artifact@v3
      with:
        name: super-sast-artifact
        path: |
          super-sast.log
          log_dir/
